version: "3.7"
services:
  flume:
    build: ./flume
    container_name: flume
    ports:
      - "1234:1234"
    networks: 
      - confluent
  kafka-hadoop:
    build: ./kafka-hadoop
    container_name: kafka-hadoop
    networks: 
      - confluent
  sentiment:
    image: graham3333/corenlp-complete
    container_name: sentiment
    networks: 
      - confluent

networks:
  confluent: