version: "3.7"
services:
  flume:
    build: ./flume
    container_name: flume
    ports:
      - "1234:1234"
    networks: 
      - confluent

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    container_name: zookeeper
    environment: 
      - ZOOKEEPER_CLIENT_PORT=2181
    networks: 
      - confluent

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    container_name: kafka
    environment: 
      - ZOOKEEPER_CLIENT_PORT=2181
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    networks: 
      - confluent
  
  sentiment:
    image: graham3333/corenlp-complete
    container_name: sentiment
    networks: 
      - confluent
  spark:
    image: hoanglt705/spark-optimize
    container_name: spark
    privileged: true
    hostname: quickstart.cloudera
    command: /usr/bin/docker-quickstart
    tty: true
    stdin_open: true  
    networks: 
      - confluent
networks:
  confluent:
    name: confluent