version: "3.7"
services:
  flume:
    build: ./flume
    container_name: flume
    ports:
      - "1234:1234"
    networks: 
      - confluent

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    container_name: zookeeper
    environment: 
      - ZOOKEEPER_CLIENT_PORT=2181
    networks: 
      - confluent

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    container_name: kafka
    environment: 
      - ZOOKEEPER_CLIENT_PORT=2181
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks: 
      - confluent

  spark:
    image: antlypls/spark:1.5.1
    container_name: spark
    command: /etc/bootstrap.sh
    volumes:
      - ./volumes/spark:/app
    networks: 
      - confluent
networks:
  confluent: