kubectl delete deployments flume-deployment
kubectl delete services flume-service
kubectl delete deployments kafka-deployment
kubectl delete services kafka-service
kubectl delete deployments zookeeper-deployment
kubectl delete services zookeeper
kubectl delete deployments spark-deployment
kubectl delete services spark
kubectl delete deployments sentiment-deployment
kubectl delete services sentiment