apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-pod 
      app: kafka-app
  template:
    metadata:
      name: kafka-pod
      labels:
        name: kafka-pod
        app: kafka-app
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:5.0.0
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka:9092"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
        ports:
        - containerPort: 9092
