apiVersion: v1
kind: Service
metadata:
  name: sentiment
  labels:
    name: sentiment
    app: sentiment-app
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30007
  selector:
    name: sentiment-pod
    app: sentiment-app
